font_faces = {
'Akshar Unicode':            ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Annamayya':                 ['Regular', 'Bold', 'Italic', 'Bold Italic'], 
'Chathura':                  ['Thin', 'Light', 'Regular', 'ExtraBold', 'Bold', 'Italic', 'Bold', 'Bold Italic'], 
'Dhurjati':                  ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'GIST-TLOTAmma':             ['Normal', 'Bold', 'Italic', 'Bold Italic'], 
'GIST-TLOTAmruta':           ['Bold', 'Bold Italic'], 
'GIST-TLOTAtreya':           ['Normal', 'Bold', 'Italic', 'Bold Italic'], 
'GIST-TLOTChandana':         ['Bold', 'Bold Italic'], 
'GIST-TLOTDeva':             ['Normal', 'Bold', 'Bold Italic', 'Italic'], 
'GIST-TLOTDraupadi':         ['Regular', 'Bold', 'Italic', 'Bold Italic'], 
'GIST-TLOTGolkonda':         ['Bold', 'Bold Italic'], 
'GIST-TLOTKrishna':          ['Normal', 'Bold Italic', 'Bold', 'Italic'], 
'GIST-TLOTManu':             ['Normal', 'Bold', 'Italic', 'Bold Italic'], 
'GIST-TLOTMenaka':           ['Normal', 'Bold', 'Italic', 'Bold Italic'], 
'GIST-TLOTPavani':           ['Bold', 'Bold Italic'], 
'GIST-TLOTPriya':            ['Bold', 'Bold Italic'], 
'GIST-TLOTRajan':            ['Bold', 'Bold Italic'], 
'GIST-TLOTRajani':           ['Bold', 'Bold Italic'], 
'GIST-TLOTSanjana':          ['Bold', 'Bold Italic'], 
'GIST-TLOTSitara':           ['Bold', 'Bold Italic'], 
'GIST-TLOTSwami':            ['Bold', 'Bold', 'Bold Italic'], 
'GIST-TLOTVennela':          ['Normal', 'Bold', 'Italic', 'Bold Italic'], 
'Gautami':                   ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Gidugu':                    ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'Gurajada':                  ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'JIMS':                      ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'Kanaka Durga':              ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'LakkiReddy':                ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Lohit Telugu':              ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Mallanna':                  ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'Mandali':                   ['Regular', 'Bold', 'Italic', 'Bold Italic'], 
'NATS':                      ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'NTR':                       ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'Nandakam':                  ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'Nandini3':                  ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Nirmala UI':                ['Semilight', 'Regular', 'Italic', 'Bold Italic', 'Bold'], 
'Noto Sans Telugu':          ['Regular', 'Italic', 'Bold Italic', 'Bold'], 
'Peddana':                   ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Ponnala':                   ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Pothana2000':               ['Regular', 'Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Potti Sreeramulu':          ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Purushothamaa':             ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'Ramabhadra':                ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'RamaneeyaWin':              ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Ramaraja':                  ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'RaviPrakash':               ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'SURAVARA_Swarna':           ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Sree Krushnadevaraya':      ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'Subhadra':                  ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Suguna':                    ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'SuraVara_Samhita':          ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Suranna':                   ['Regular', 'Bold', 'Italic', 'Bold Italic'], 
'Suravaram':                 ['Regular', 'Bold', 'Bold Italic', 'Italic'], 
'Syamala Ramana':            ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'TenaliRamakrishna':         ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Timmana':                   ['Bold Italic', 'Regular'], 
'Vajram':                    ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
'Vani':                      ['Regular', 'Italic', 'Bold Italic', 'Bold'], 
'Vemana2000':                ['Regular', 'Regular', 'Italic', 'Bold', 'Bold Italic'], 
'e-Telugu OT':               ['Regular', 'Italic', 'Bold', 'Bold Italic'], 
}